/*
Run this script on:

        (local)\SQLEXPRESS.C:\USERS\STAMBOUR\APPDATA\LOCAL\SISTEMACINDERELLADESARROLLO\CINDERELLA_LOCAL.MDF    -  This database will be modified

to synchronize it with:

        (local)\SQLEXPRESS.CINDERELLA_LOCAL

You are recommended to back up your database before running this script

Script created by SQL Compare version 14.2.9.15508 from Red Gate Software Ltd at 11/2/2021 23:20:06

*/
SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL Serializable
GO
BEGIN TRANSACTION
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Altering [dbo].[NUEVA_NOTA_PEDIDO]'
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
IF COL_LENGTH(N'[dbo].[NUEVA_NOTA_PEDIDO]', N'Comentarios') IS NULL
ALTER TABLE [dbo].[NUEVA_NOTA_PEDIDO] ADD[Comentarios] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Altering [dbo].[NUEVA_NOTA_PEDIDO_ITEMS]'
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
IF COL_LENGTH(N'[dbo].[NUEVA_NOTA_PEDIDO_ITEMS]', N'Borrado') IS NULL
ALTER TABLE [dbo].[NUEVA_NOTA_PEDIDO_ITEMS] ADD[Borrado] [bit] NULL CONSTRAINT [DF_NUEVA_NOTA_PEDIDO_ITEMS_Borrado] DEFAULT ((0))
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Enabling constraints on [dbo].[NUEVA_CLIENTE_MAYORISTA_DOCUMENTO_PAGO_PAGO]'
GO
IF EXISTS (SELECT 1 FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_NUEVA_CLIENTE_MAYORISTA_DOCUMENTO_PAGO_PAGO_NUEVA_CLIENTE_MAYORISTA_DOCUMENTO_PAGO]','F') AND parent_object_id = OBJECT_ID(N'[dbo].[NUEVA_CLIENTE_MAYORISTA_DOCUMENTO_PAGO_PAGO]', 'U'))
ALTER TABLE [dbo].[NUEVA_CLIENTE_MAYORISTA_DOCUMENTO_PAGO_PAGO] NOCHECK CONSTRAINT [FK_NUEVA_CLIENTE_MAYORISTA_DOCUMENTO_PAGO_PAGO_NUEVA_CLIENTE_MAYORISTA_DOCUMENTO_PAGO]
GO
ALTER TABLE [dbo].[NUEVA_CLIENTE_MAYORISTA_DOCUMENTO_PAGO_PAGO] CHECK CONSTRAINT [FK_NUEVA_CLIENTE_MAYORISTA_DOCUMENTO_PAGO_PAGO_NUEVA_CLIENTE_MAYORISTA_DOCUMENTO_PAGO]
GO
IF EXISTS (SELECT 1 FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_NUEVA_CLIENTE_MAYORISTA_DOCUMENTO_PAGO_PAGO_NUEVA_CUENTABANCARIA]','F') AND parent_object_id = OBJECT_ID(N'[dbo].[NUEVA_CLIENTE_MAYORISTA_DOCUMENTO_PAGO_PAGO]', 'U'))
ALTER TABLE [dbo].[NUEVA_CLIENTE_MAYORISTA_DOCUMENTO_PAGO_PAGO] NOCHECK CONSTRAINT [FK_NUEVA_CLIENTE_MAYORISTA_DOCUMENTO_PAGO_PAGO_NUEVA_CUENTABANCARIA]
GO
ALTER TABLE [dbo].[NUEVA_CLIENTE_MAYORISTA_DOCUMENTO_PAGO_PAGO] CHECK CONSTRAINT [FK_NUEVA_CLIENTE_MAYORISTA_DOCUMENTO_PAGO_PAGO_NUEVA_CUENTABANCARIA]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
PRINT N'Enabling constraints on [dbo].[NUEVA_VENTA_PAGOS]'
GO
IF EXISTS (SELECT 1 FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_NUEVA_VENTA_PAGOS_NUEVA_CUENTABANCARIA]','F') AND parent_object_id = OBJECT_ID(N'[dbo].[NUEVA_VENTA_PAGOS]', 'U'))
ALTER TABLE [dbo].[NUEVA_VENTA_PAGOS] NOCHECK CONSTRAINT [FK_NUEVA_VENTA_PAGOS_NUEVA_CUENTABANCARIA]
GO
ALTER TABLE [dbo].[NUEVA_VENTA_PAGOS] CHECK CONSTRAINT [FK_NUEVA_VENTA_PAGOS_NUEVA_CUENTABANCARIA]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
COMMIT TRANSACTION
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
-- This statement writes to the SQL Server Log so SQL Monitor can show this deployment.
IF HAS_PERMS_BY_NAME(N'sys.xp_logevent', N'OBJECT', N'EXECUTE') = 1
BEGIN
    DECLARE @databaseName AS nvarchar(2048), @eventMessage AS nvarchar(2048)
    SET @databaseName = REPLACE(REPLACE(DB_NAME(), N'\', N'\\'), N'"', N'\"')
    SET @eventMessage = N'Redgate SQL Compare: { "deployment": { "description": "Redgate SQL Compare deployed to ' + @databaseName + N'", "database": "' + @databaseName + N'" }}'
    EXECUTE sys.xp_logevent 55000, @eventMessage
END
GO
DECLARE @Success AS BIT
SET @Success = 1
SET NOEXEC OFF
IF (@Success = 1) PRINT 'The database update succeeded'
ELSE BEGIN
	IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
	PRINT 'The database update failed'
END
GO
