SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
GO
SET DATEFORMAT YMD
GO
SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL Serializable
GO
BEGIN TRANSACTION

IF EXISTS (SELECT * FROM [NUEVA_FACTURA] WHERE [CondicionIVA] = 0) 
BEGIN
   update [NUEVA_FACTURA]
set [CondicionIVA] = [CondicionIVA] + 1
END

COMMIT TRANSACTION
GO
