USE [CINDERELLA]
GO

/****** Object:  Table [dbo].[DIRECCION]    Script Date: 12/02/2017 03:57:02 p.m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[DIRECCION](
	[id_Direccion] [int] IDENTITY(1,1) NOT NULL,
	[Direccion] [varchar](255) NULL,
	[id_Provincia] [int] NULL,
	[id_Distrito] [int] NULL,
	[id_Localidad] [int] NULL,
	[CodigoPostal] [varchar](255) NULL,
	[Telefono] [varchar](255) NULL,
	[Mail] [varchar](255) NULL,
 CONSTRAINT [PK_Direccion] PRIMARY KEY CLUSTERED 
(
	[id_Direccion] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[DIRECCION]  WITH CHECK ADD  CONSTRAINT [FK_Direccion_DEPARTAMENTOS] FOREIGN KEY([id_Distrito])
REFERENCES [dbo].[DEPARTAMENTOS] ([id_Departamento])
GO

ALTER TABLE [dbo].[DIRECCION] CHECK CONSTRAINT [FK_Direccion_DEPARTAMENTOS]
GO

ALTER TABLE [dbo].[DIRECCION]  WITH CHECK ADD  CONSTRAINT [FK_Direccion_LOCALIDADES] FOREIGN KEY([id_Localidad])
REFERENCES [dbo].[LOCALIDADES] ([id_Localidad])
GO

ALTER TABLE [dbo].[DIRECCION] CHECK CONSTRAINT [FK_Direccion_LOCALIDADES]
GO

ALTER TABLE [dbo].[DIRECCION]  WITH CHECK ADD  CONSTRAINT [FK_Direccion_PROVINCIAS] FOREIGN KEY([id_Provincia])
REFERENCES [dbo].[PROVINCIAS] ([id_Provincia])
GO

ALTER TABLE [dbo].[DIRECCION] CHECK CONSTRAINT [FK_Direccion_PROVINCIAS]
GO

